name: solhint-ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  solhint:
    name: runner / solhint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run solhint with contracthsark
        uses: contractshark/inject-solhint-ci@1.0.0+0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          solhint_input: 'packages/hardhat/contracts/**/*.sol'
