name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Test Coverage
        run: |
          # BLOCK_NUMBER=86630670 yarn test test/radiantArbitrumVaultTest.js
          BLOCK_NUMBER=97022421 yarn test test/dpxArbitrumVaultTest.js
          BLOCK_NUMBER=97016882 yarn test test/radiantDlpVaultTest.js