name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Test
        run: |
          # block_number=$(curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' ${{ secrets.ARBITRUM_RPC }} | jq -r '.result')
          # DECIMAL_BLOCK_NUMBER=$(printf "%d" "$block_number")
          BLOCK_NUMBER=118979128 yarn test test/permanentPortfolioTest.js;
          BLOCK_NUMBER=118979128 yarn test test/permanentPortfolioRewardTest.js;
          BLOCK_NUMBER=118979128 yarn test test/feeTest.js;
          BLOCK_NUMBER=118979128 yarn test test/dpxArbitrumVaultTest.js;
          BLOCK_NUMBER=118979128 yarn test test/equilibriaGLP.js;
          BLOCK_NUMBER=118979128 yarn test test/equilibriaGDAI.js;
          BLOCK_NUMBER=118979128 yarn test test/updateRewardsTest.js


          # # BLOCK_NUMBER=$DECIMAL_BLOCK_NUMBER yarn test test/radiantDlpVaultTest.js;
          # # BLOCK_NUMBER=$DECIMAL_BLOCK_NUMBER yarn test test/radiantDlpVaultRewardTest.js;

          # # TODO(david): test all weather portfolio in Beta verion
          # # BLOCK_NUMBER=$DECIMAL_BLOCK_NUMBER yarn test test/allWeatherPortfolioTest.js
          # # BLOCK_NUMBER=$DECIMAL_BLOCK_NUMBER yarn test test/allWeatherPortfolioRewardTest.js
