name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Test
        run: |
          BLOCK_NUMBER=127196756 yarn test test/feeTest.js;
          # BLOCK_NUMBER=127196756 yarn test test/dpxArbitrumVaultTest.js;
          BLOCK_NUMBER=127196756 yarn test test/magicArbitrumVaultTest.js;
          BLOCK_NUMBER=127196756 yarn test test/updateRewardsTest.js
          BLOCK_NUMBER=127196756 yarn test/updateRewardsTestPart2_merge_would_fail_I_dont_know_why.js
          BLOCK_NUMBER=127196756 yarn test test/equilibriaGLP.js;
          BLOCK_NUMBER=127196756 yarn test test/equilibriaGDAI.js;
          BLOCK_NUMBER=127196756 yarn test test/equilibriaRETH.js;
          BLOCK_NUMBER=127196756 yarn test test/permanentPortfolioTest.js;
          BLOCK_NUMBER=127196756 yarn test test/permanentPortfolioRewardTest.js;


          # # BLOCK_NUMBER=$DECIMAL_BLOCK_NUMBER yarn test test/radiantDlpVaultTest.js;
          # # BLOCK_NUMBER=$DECIMAL_BLOCK_NUMBER yarn test test/radiantDlpVaultRewardTest.js;

          # # TODO(david): test all weather portfolio in Beta verion
          # # BLOCK_NUMBER=$DECIMAL_BLOCK_NUMBER yarn test test/allWeatherPortfolioTest.js
          # # BLOCK_NUMBER=$DECIMAL_BLOCK_NUMBER yarn test test/allWeatherPortfolioRewardTest.js
