name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Test
        run: |
          BLOCK_NUMBER=107716130 yarn test test/dpxArbitrumVaultTest.js;
          BLOCK_NUMBER=107716130 yarn test test/radiantDlpVaultTest.js;
          BLOCK_NUMBER=107716130 yarn test test/radiantDlpVaultRewardTest.js;
          BLOCK_NUMBER=107716130 yarn test test/equilibriaGLP.js;
          BLOCK_NUMBER=107716130 yarn test test/equilibriaGDAI.js;